Add hooks functionality
CollinsTatang/math-magicians pull request #4
Opened 2021-08-12 14:12 UTC by CollinsTatang

**This branch required the following:**
- To refactor the Calculator component from a class-based component to a functional component with hooks.

2021-08-12 16:54 UTC, henatan99 requested changes
Hi @CollinsTatang , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-12 16:54 UTC, henatan99 commented on src/component/Calculator.js
> +      </div>
- [ ] There are errors on the browser when a number is divided by zero or when an operator is clicked twice. As your app should work without errors please incorporate some error handling for `displayNum`. 
![Screenshot from 2021-08-12 22-50-28](https://user-images.githubusercontent.com/64894927/129236603-6b50938b-9455-4585-b5a1-9d6531467dc1.png)
![Screenshot from 2021-08-12 22-50-18](https://user-images.githubusercontent.com/64894927/129236604-5f07f120-0859-4f70-88e1-9605ccd9a36a.png)

2021-08-13 09:36 UTC, Dipeshtwis approved these changes
# Status: Approved ✔️

## Hi @CollinsTatang, 

Good job on implementing the suggested changes. Well Done.
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

**You may close this Pull Request and merge the changes**

  
**Keep being awesome devs and good luck with your next milestone!**
---------

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
_**Dipesh Kumar**_

--------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-13 09:46 UTC, CollinsTatang commented
Hi @henatan99 and @Dipeshtwis 
Thanks for the review massage.

2021-08-13 10:10 UTC, merged